fix: Exclude build wheel for cp38-macosx_arm64
because of error

/Users/runner/work/dlib-compiled/dlib-compiled/dlib/external/libpng/arm/../pngpriv.h:527:16: fatal error: 'fp.h' file not found
          527 | #      include <fp.h>