fix: Because of minimum target of 15.0
Error:   Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=15.0' to update minimum supported macOS for this wheel.